packages:
  - 'packages/*'
  - 'apps/*'

allowBuilds:
  '@google/genai': true
  esbuild: false
  protobufjs: true
  sharp: false

minimumReleaseAgeExclude:
  - '@aws-sdk/client-s3@3.1107.0'
  - '@aws-sdk/s3-request-presigner@3.1107.0'
