packages:
  - 'packages/*'
  - 'apps/*'

overrides:
  '@langchain/langgraph>@langchain/langgraph-checkpoint': 1.0.0
  '@langchain/langgraph>@langchain/langgraph-sdk': 1.7.1

allowBuilds:
  '@google/genai': true
  esbuild: false
  protobufjs: true
  sharp: false

minimumReleaseAgeExclude:
  - '@aws-sdk/client-s3@3.1107.0'
  - '@aws-sdk/s3-request-presigner@3.1107.0'
