"use client";

import { useEffect, useMemo, useState } from "react";
import { Archive, Brain, Check, Pencil, RefreshCw, RotateCcw } from "lucide-react";
import { AppSidebar } from "../../components/app-sidebar";
import { memoryApi, type MemoryEntry } from "../../api";
import styles from "./memory.module.css";

const slots = ["profile", "preferences", "scope", "recent"] as const;
const labels: Record<string, string> = { profile: "关于你", preferences: "学习偏好", scope: "学习范围", recent: "最近学习" };

export default function MemoryPage() {
  const [entries, setEntries] = useState<MemoryEntry[]>([]); const [showArchived, setShowArchived] = useState(false);
  const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [editing, setEditing] = useState<string | null>(null); const [draft, setDraft] = useState(""); const [saving, setSaving] = useState(false); const [notice, setNotice] = useState<string | null>(null);
  useEffect(() => { setLoading(true); void memoryApi.list({ layer: "L3", includeArchived: showArchived }).then((result) => setEntries(result.entries)).catch((e) => setError(e instanceof Error ? e.message : "记忆加载失败")).finally(() => setLoading(false)); }, [showArchived]);
  const grouped = useMemo(() => Object.fromEntries(slots.map((slot) => [slot, entries.filter((entry) => entry.slot === slot)])), [entries]);
  function beginEdit(entry: MemoryEntry) { setEditing(entry.id); setDraft(entry.text); setNotice(null); }
  async function save(id: string) { if (!draft.trim()) return; setSaving(true); try { const result = await memoryApi.update(id, { text: draft.trim() }); setEntries((all) => all.map((entry) => entry.id === id ? result.entry : entry)); setEditing(null); setNotice("记忆已更新"); } catch (e) { setError(e instanceof Error ? e.message : "保存失败"); } finally { setSaving(false); } }
  async function archive(id: string, status: "active" | "archived") { try { const result = await memoryApi.update(id, { status }); setEntries((all) => showArchived ? all.map((entry) => entry.id === id ? result.entry : entry) : all.filter((entry) => entry.id !== id)); setNotice(status === "archived" ? "已归档，可从历史记录恢复" : "已恢复"); } catch (e) { setError(e instanceof Error ? e.message : "操作失败"); } }
  async function updateConsolidation() { setLoading(true); setError(null); try { const result = await memoryApi.consolidate(); const refreshed = await memoryApi.list({ layer: "L3", includeArchived: showArchived }); setEntries(refreshed.entries); setNotice(`记忆已更新：处理 ${result.run.processed} 条活动，新增 ${result.run.added} 条记忆`); } catch (e) { setError(e instanceof Error ? e.message : "更新学习记忆失败"); } finally { setLoading(false); } }
  return <main className={styles.page}><AppSidebar activeSection="memory" historyMode="chat" /><section className={styles.content}><div className={styles.inner}><header className={styles.header}><div><span className={styles.kicker}>Chalk / Memory</span><h1>学习记忆</h1><p>你可以查看和修改 Chalk 为你整理的长期学习偏好与上下文。</p></div><div className={styles.headerTools}><button type="button" onClick={() => void updateConsolidation()} disabled={loading}><RefreshCw size={13} />{loading ? "更新中…" : "立即 Update"}</button><button type="button" onClick={() => setShowArchived((value) => !value)}>{showArchived ? "隐藏已归档" : "查看已归档"}</button><Brain size={24} className={styles.headerIcon} /></div></header>{error && <p className={styles.error} role="alert">{error}</p>}{notice && <p className={styles.notice} role="status"><Check size={15} />{notice}</p>}{loading ? <div className={styles.empty}>正在加载记忆…</div> : <div className={styles.sections}>{slots.map((slot) => <section key={slot} className={styles.section}><div className={styles.sectionHeading}><h2>{labels[slot]}</h2><span>{grouped[slot].length}</span></div>{grouped[slot].length ? grouped[slot].map((entry) => <article className={`${styles.entry} ${entry.status === "archived" ? styles.archived : ""}`} key={entry.id}>{editing === entry.id ? <div className={styles.editRow}><textarea value={draft} onChange={(e) => setDraft(e.target.value)} maxLength={240} autoFocus /><div className={styles.actions}><button type="button" onClick={() => setEditing(null)}>取消</button><button className={styles.primary} type="button" disabled={saving || !draft.trim()} onClick={() => void save(entry.id)}>{saving ? "保存中…" : "保存"}</button></div></div> : <><p>{entry.text}</p><div className={styles.meta}><span>更新于 {new Date(entry.updatedAt).toLocaleDateString("zh-CN")} · 来源 {entry.refs.length} 条 {entry.status === "archived" ? "· 已归档" : ""}</span><span className={styles.entryActions}><button type="button" onClick={() => beginEdit(entry)} aria-label="编辑记忆"><Pencil size={14} /></button>{entry.status === "archived" ? <button type="button" onClick={() => void archive(entry.id, "active")} aria-label="恢复记忆"><RotateCcw size={14} /></button> : <button type="button" onClick={() => void archive(entry.id, "archived")} aria-label="归档记忆"><Archive size={14} /></button>}</span></div></>}</article>) : <p className={styles.sectionEmpty}>还没有内容</p>}</section>)}</div>}{!loading && <footer className={styles.footer}><RotateCcw size={14} />记忆只用于帮助教学，不代表对知识掌握度的判定。</footer>}</div></section></main>;
}
