import { createHmac } from 'node:crypto';
import { mapHttpError, ProviderError, readJsonObject } from '../../provider-error';
import type { VideoAdapter, VideoInput, VideoPollOutput, VideoSubmitOutput } from '../types';

export class KlingVideoAdapter implements VideoAdapter {
  private readonly fetcher: typeof globalThis.fetch;
  constructor(private readonly options: { apiKey: string; baseUrl: string; fetch?: typeof globalThis.fetch; timeoutMs?: number }) { this.fetcher = options.fetch ?? globalThis.fetch; if (!options.apiKey.includes(':')) throw new Error('Kling API key must be accessKey:secretKey'); }
  private token() { const [accessKey, secretKey] = this.options.apiKey.split(':'); const enc = (value: string) => Buffer.from(value).toString('base64url'); const header = enc(JSON.stringify({ alg: 'HS256', typ: 'JWT' })); const now = Math.floor(Date.now() / 1000); const payload = enc(JSON.stringify({ iss: accessKey, exp: now + 1800, nbf: now - 5, iat: now })); return `${header}.${payload}.${createHmac('sha256', secretKey!).update(`${header}.${payload}`).digest().toString('base64url')}`; }
  async submit(input: VideoInput): Promise<VideoSubmitOutput> { const response = await this.fetcher(`${this.options.baseUrl.replace(/\/$/, '')}/v1/videos/text2video`, { method: 'POST', headers: { authorization: `Bearer ${this.token()}`, 'content-type': 'application/json' }, body: JSON.stringify({ model_name: input.model ?? 'kling-v2-6', prompt: input.prompt, negative_prompt: '', mode: 'pro', ...(input.durationSeconds ? { duration: String(input.durationSeconds) } : {}), ...(input.aspectRatio ? { aspect_ratio: input.aspectRatio } : {}) }), signal: input.signal ?? AbortSignal.timeout(this.options.timeoutMs ?? 60_000) }); if (!response.ok) throw mapHttpError(response.status, 'Kling'); const data = await readJsonObject(response, 'Kling'); const taskId = (data.data as { task_id?: unknown } | undefined)?.task_id; if (typeof taskId !== 'string' || !taskId) throw new ProviderError('MALFORMED_RESPONSE', 'Kling returned no task id', true); return { providerTaskId: taskId }; }
  async poll(providerTaskId: string, signal?: AbortSignal): Promise<VideoPollOutput> { const response = await this.fetcher(`${this.options.baseUrl.replace(/\/$/, '')}/v1/videos/text2video/${encodeURIComponent(providerTaskId)}`, { headers: { authorization: `Bearer ${this.token()}` }, signal: signal ?? AbortSignal.timeout(this.options.timeoutMs ?? 60_000) }); if (!response.ok) throw mapHttpError(response.status, 'Kling'); const data = await readJsonObject(response, 'Kling'); const result = (data.data as { task_status?: string; task_result?: { videos?: Array<{ url?: unknown; duration?: string }> } } | undefined); if (result?.task_status === 'succeed' && typeof result.task_result?.videos?.[0]?.url === 'string') return { status: 'done', url: result.task_result.videos[0].url, contentType: 'video/mp4', durationSeconds: Number(result.task_result.videos[0].duration) || undefined }; if (result?.task_status === 'failed') return { status: 'failed', error: new ProviderError('UPSTREAM_FAILED', 'Kling video generation failed', false) }; return { status: 'pending' }; }
  async testConnection(_model?: string) { const response = await this.fetcher(`${this.options.baseUrl.replace(/\/$/, '')}/v1/videos/text2video/connectivity-test`, { headers: { authorization: `Bearer ${this.token()}` } }); if (response.status === 401 || response.status === 403) throw mapHttpError(response.status, 'Kling'); }
}
